name: Deploy Just the Docs to GitHub Pages

on:
  push:
    branches:
      - main # Adjust if your default branch is not `main`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1 # Use a compatible version

    - name: Install Dependencies
      run: bundle install

    - name: Build the Site
      run: bundle exec jekyll build
      env:
        JEKYLL_ENV: production

    - name: Deploy to GitHub Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./_site # Path to the Jekyll output directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

